name: RT-ProjectManager
version: 0.01_01
abstract: RT ProjectManager Extension
author: Jesse Vincent <jesse@bestpractical.com>
license: GPLv2
distribution_type: module
no_index:
  directory:
    - html
    - inc
generated_by: Module::Install version 0.33
